### ISSUE TITLE
Need the feature for TSV file read.

### ISSUE THREAD

**Issue by Gayanthakaushal** [siddhi-io/siddhi-io-file#152]
**Description:**
Currently, siddhi does not have support for the TSV file reading.  Since some use cases need to read the TSV files using siddhi if it is better if we can add this feature for siddhi.

**Suggested Labels:**
streaming-integrator-1.1.0

**Comment by lasanthaS** [comment]
Closing this issue as the issue is fixed by https://github.com/siddhi-io/siddhi-map-csv/pull/34
