### ISSUE TITLE
Can't give a directory for file source when using tailing mode

### ISSUE THREAD

**Issue by niruhan** [siddhi-io/siddhi-io-file#71]
**Description:**
When tailing is disabled, we can specify dir.uri and give an empty folder and start the server. During runtime, we can copy a data file to the specified directory and the file will get picked up and start reading. However, when tailing is enabled we cannot specify a dir.uri but we have to give a file.uri="foo/bar.txt". A specific file name should be given and that file should be available in the directory before the server starts. 

**Affected Product Version:**
siddhi-io-file 1.1.1

**Steps to reproduce:**
use the following siddhi app
```
@App:name("testAppTwo")
@App:description("Description of the plan")
-- Please refer to https://docs.wso2.com/display/SP400/Quick+Start+Guide on getting started with SP editor.

@source(type = 'file', dir.uri = 'file:/Users/niruhan/My_Tasks/task5_filePatch/source', move.after.failure = 'file:/Users/niruhan/My_Tasks/task5_filePatch/failure', mode = 'LINE', tailing = 'true', action.after.failure = 'MOVE', add.event.separator = 'false', @map(type = 'csv')) 
define stream FooStream (attr1 int);

define stream OutputStream (attr1 int);

@info(name = 'SiddhiApp2') 
from FooStream#log("READ_VALUES")
select *
insert into OutputStream;
```

start the server. copy a file with the following contents into the dir.uri specified
```
1
2
3
4
```

**Related Issues:**
https://github.com/wso2/product-sp/issues/1047

**Comment by mohanvive** [comment]
It was decided to not to support tailing capability for a directory. It is only support for a file..
