### ISSUE TITLE
NullPointer Exception when changing states (Run/ Stop) in Tooling

### ISSUE THREAD

**Issue by ramindu90** [siddhi-io/siddhi-io-file#89]
**Description:**
When using any file extension in the tooling and if we start and stop the siddhi application several times really fast, then it give a NullPointerException.

**Steps to reproduce:**
Deploy CSVDefaultMapping sample in the tooling.
Click on start and play button at a fast rate.

**Comment by Ajanthy** [comment]
The issue is fixed in https://github.com/siddhi-io/siddhi-io-file/commit/9b46545dc295775c87bd6e9db02f48f8b71a72a4
